### ISSUE TITLE
(US7.2 VALORAR) Backend: añadir calculo media de rating

### ISSUE THREAD

**Issue by PauRodriguezTrens** [UB-ES-2022-B2/Doogking#123]

**Comment by aniolgarcia** [comment]
Tancat per #171. Es pot afegir una nova valoració fent un POST a `/api/update_rating/<house_id>/` amb data `{"rating":<rating>}`. Al model i a backend es fa servir un Decimal amb precissió de 4 decimals però quan es serialitza a Housing es fa un round per passar-lo a integer, que frontend no pot mostrar valoracions amb decimals.
