### ISSUE TITLE
(US.20 Ver casas que me han reservado) Backend

### ISSUE THREAD

**Issue by PauRodriguezTrens** [UB-ES-2022-B2/Doogking#127]

**Comment by aniolgarcia** [comment]
Tal com a #129, per #74 hi ha l'enpoint `/api/reservations/?owner=<user_id>`, que dóna una llista de les reserves només de les cases en les que el propietari és l'usuari amb id passat. No es dóna una llista d'instàncies úniques de cases, sinó totes les reserves.

**Comment by aniolgarcia** [comment]
Tancat per #74
