### ISSUE TITLE
(US.18 Ver mis casas) Backend

### ISSUE THREAD

**Issue by PauRodriguezTrens** [UB-ES-2022-B2/Doogking#131]

**Comment by aniolgarcia** [comment]
Fet a 9e22772557116096a244eefa02588c188cb9a997.

Es poden obtenir les cases d'un usuari per l'endpoint `/api/housing/?owner=<user_id>/`. Veure #136 per a més detalls.

**Comment by aniolgarcia** [comment]
Tancat per #185
