### ISSUE TITLE
Estilización de la vista de "ForgotPassword"

### ISSUE THREAD

**Issue by DanielYeste** [UB-ES-2022-B2/Doogking#21]

**Comment by mariaroman99** [comment]
La pagina ForgotPassword ya esta hecho acorde con la estetica del login y registro y con el header y footer. También he añadido en login el boton de forgot Password para redirigir a la página de restuaruación de contraseña

**Comment by mariaroman99** [comment]
En esta página se muestra una card con un campo input en el que se introduce el mail del usuario para poder recuperar la contraseña. Cuando se clica el boton submit, se le envia un correo a dicho usuario para recuperar la contraseña.
