### ISSUE TITLE
(US.2 PUBLICAR) Backend: Añadir casa a la base de datos

### ISSUE THREAD

**Issue by PauRodriguezTrens** [UB-ES-2022-B2/Doogking#65]
Crar POST para endpoint Housing que permita enviar a backend los datos de la casa junto con su imagen (url de imagen guardada previamente en Azure)

**Comment by aniolgarcia** [comment]
El post de housing està funcionant a l'endpoint `/api/houing/`. Les imatges de cada casa no es guarden al model de housing, sinó que es gestionen per separat. Primer s'han de pujar a azure mitjançant l'endpoint `/api/upload/` (veure la view `UploaderView` de 62f74127b05c53d40b3c68e0a7335d4a2bd3195a), que retorna el nom amb el que es puja a azure. Un cop a azure, es vinculen a la casa a partir de la taula HousingImage, a nivell d'api només cal fer un POST a `/api/housing_images/` amb la id de la casa, la url d'azure de la imatge i l'índex de la imatge (veure #74 per a més detalls).

**Comment by aniolgarcia** [comment]
**EDIT:** Pel commit 850fa44d144800a6bd5aaddd7396d59f02535881, l'endpoint per pujar imatges no és a `/api/upload/`, sinó a `/api/uploadProfile/`(?). S'hauria de tornar a posar `/api/upload/`, ja que no està restringit a profile, és general per pujar imatges a azure

**Comment by aniolgarcia** [comment]
**EDIT2:** Pel commit b5074460fea83d6cad79dc49dd96c8c469158015, ja hi ha l'endpoint `/api/upload/` i per #108 ja és a integration, per tant queda tancat.
