### ISSUE TITLE
(US.6.1 PERFIL) Backend: Añadir foto perfil

### ISSUE THREAD

**Issue by PauRodriguezTrens** [UB-ES-2022-B2/Doogking#67]
Modificar el model Profile per afegir-hi una imatge de perfil

**Comment by aniolgarcia** [comment]
A nivell de backend cal:
- Afegir un camp `ImageField` per emmagatzemar una imatge. Aquesta imatge s'ha de guardar a azure, potser no al directori arrel del blob storage si no a un subdirectori (profiles/, profile_images/ o alguna cosa per l'estil), per separar-les de les de housing.
-  Fer la migració de django (incremental respecte els que ja hi ha a integration).
- Afegir el camp image al serializer de profile
- Crear els endpoints per pujar-la (veure la implementació que tenim a PUBLICAR per una guia de com fer-ho, tant a nivell de frontend com de backend)
