### ISSUE TITLE
(US.6.1 CAMBIAR CONTRASEÑA) Backend: Cambiar contraseña

### ISSUE THREAD

**Issue by PauRodriguezTrens** [UB-ES-2022-B2/Doogking#68]
Desde la página principal el usuario (logeado) debe poder clicar en “View profile” desde un dropdown en la parte superior derecha de la barra de navegación.

**Comment by aniolgarcia** [comment]
S'hauria de crear un nou endpoint que permetés canviar la contrassenya, que amb el PATCH tradicional no és suficient. Només s'ha de permetre el canvi de contrassenya d'un usuari a aquell usuari (comprovar que les id de la request i l'endpoint quadrin) i potser a l'administrador.
