### ISSUE TITLE
(US.6.1 PERFIL) Backend: Editar perfil

### ISSUE THREAD

**Issue by PauRodriguezTrens** [UB-ES-2022-B2/Doogking#69]

**Comment by aniolgarcia** [comment]
Actualment implementat parcialment mitjançant requests PATCH a l'endpoint `/api/profiles/<id_profile>/`,  tot i que només en té permís l'usuari administrador. Caldria afegir al mètode de `get_queryset()` del ModelViewSet de profile un comprovació de si la id de l'usuari que fa la request coincideix amb la id de l'usuari sobre el que es fa la request (la id que es passa a l'endpoint) i, en cas que coincideixin, atribuir-li els permisos adients.

**Comment by aniolgarcia** [comment]
Arreglat per #106
