### ISSUE TITLE
(US.1 DETALLES) Backend: Añadir campos a una casa en la base de datos

### ISSUE THREAD

**Issue by PauRodriguezTrens** [UB-ES-2022-B2/Doogking#73]
Actualitzar els models referents a Housing amb la informació especificada a la US1.1 DETALLES

**Comment by aniolgarcia** [comment]
A nivell de backend els canvis necessaris són els següents:

### Creació de la taula HousingImage
Com que necessitem poder mostrar una quantitat arbitrària d'imatges, ja no les podem guardar directament al model Housing, sinó que hem de crear una taula que emmagatzemi una referència de cada imatge amb la referència de la casa a la que pertany. També hi afegirem un camp numèric d'índex, per saber en quin ordre mostrar-les. Així, una fila de la taula `HousingImage` és del tipus

| ImageField | Housing | IntegerField |
|:---:|:---:|:---:|

### Eliminació del camp `image` de Housing
Podríem mantenir el camp per emmagatzemar la imatge que mostrem a la vista general, però és tenir informació redundant. Si establim que la imatge que es mostrarà a la vista principal és la que té l'índex 0 a la taula HousingImage, podem afegir una computed property de Housing que retorni la imatge amb índex 0 per a aquella Housing de la taula HousingImage. Si a més fem que aquesta computed property tingui el mateix nom `image` que el camp actual, no haurem de modificar el frontend. 

Abans d'eliminar aquest camp, proposo fer la migració de dades de l'atribut `image` a la taula HousingImage fent el següent procediment:

- Sense eliminar `image`, crear la taula HousingImage i fer la migració de django
- Fer una migració de dades: per a cada instància de Housing a la db, crea una entrada de HousingImage que contingui la referència a Housing actual, la imatge que conté Housing i l'índex 0.
- Eliminar l'atribut `image` i fer la migració de django
- Afegitr la computed property

Seguint aquest procediment mantindrem tota la informació de quina imatge pertany a cada housing, i tot el que tenim de frontend continua funcionant sense cap intervenció.

### Afegir el camp `details`a Housing
No té cap complicació, simplement és afegir un `TextField` en lloc d'un `CharField`, que el segon està limitat en longitud i el primer no.

### Creació de la taula Reservation
Creació de la taula per mantenir un registre de les reserves. Per a cada entrada cal guardar el Housing sobre el que es fa la reserva. el Profile que fa la reserva i les dates d'entrada i sortida. Es consideren les dates d'entrada i sortida com a dies sencers, és a dir que no es considera l'hora d'entrada i sortida. Així, els camps d'una fila són


 | Housing | Profile | DateField | DateField |
|:---:|:---:|:---:|:---:|
