### ISSUE TITLE
(US.1 DETALLES) Backend: Enviar info a frontend para que se muestre

### ISSUE THREAD

**Issue by PauRodriguezTrens** [UB-ES-2022-B2/Doogking#74]
Creació dels endpoints necessaris per tractar els models de #73 a frontend

**Comment by aniolgarcia** [comment]
Actualment (commit 8d19bfd77797b418eafa5d4909a2c5f30c1268cb de la branca DETALLES) hi ha els següents endpoints referents a #73 :

### Housing
Tal com fins ara un GET a `/api/housing/` retorna la llista completa de cases, i  a `/api/housing/<id>/` retornal la informació espcífica d'una casa. L´únic canvi és que ara retorna el camp `description` amb la descripció. `image` ara és una property en lloc d'un ImageField, però és totalment transparent a l'usuari, no cal fer cap canvi.

### HousingImage
L'endpoint corresponent a aquest model és  `/api/housing_image/`, on hi ha tota la llista de ternes (housing -- image -- index). 

- Fent-ne un GET retorna la llista sencera. 
- Es pot filtrar per id de housing fent un GET de  `/api/housing_image/housing/<housing_id>/`.
- Es pot crear una nova entrada fent-ne un POST amb els camps: `'{"housing":<housing_id>, "image":<filename a azure>, "index":<index>}'`
(sempre que s'estigui autenticat, i.e. la request contingui una entrada al header amb `"Authentication":"Token <token>"`), o bé des de la interfície d'admin

### Reservation
L'endpoint d'aquest model és `/api/reservations/`. 

- Fent un GET retorna la llista sencera de reserves, amagant el camp de l'usuari que fa la reserva (client)
- Es pot filtrar de les següents maneres:
    - Per house_id, fent un GET a `/api/reservations/?housing=<housing_id>`
    - Per owner, fent un GET a `/api/reservations/?owner=<profile_id>`. En cas que l'usuari autenticat sigui l'owner pel que es filtra, també es mostrarà el camp de l'usuari que ha fet la reserva, en cas contrari, només les dates.
    - Per client, fent GET a `/api/reservations/?client=<profile_id>`. Només funcionarà si la id de l'usuari autenticat coincideix amb client_id, i en aquest cas mostrarà totes les reserves sota el seu nom.
-  Tot usuari autenticat pot fer una reserva fent POST a `/api/reservations/` amb els camps: `'{"housing":<housing_id>, "client":<user_id>, "start_date":<date>, "end_date":<date>}'`. Actualment a backend no hi ha comprovació de que no hi hagi solapament de reserves.

**Comment by aniolgarcia** [comment]
Tancat per #92
