### ISSUE TITLE
Automatitzar build i deploy (Action)

### ISSUE THREAD

**Issue by PauRodriguezTrens** [UB-ES-2022-B2/Doogking#77]
Configurar azure perquè permeti fer el deploy mitjançant actions de github i crear una action amb les següents funcionalitats_

- Build del frontend de Vue
- Migració dels model de Django
- Deploy de frontend i backend a azure

**Comment by aniolgarcia** [comment]
La migració de les bases de dades no es pot fer directament des de les actions de github ja que no hi tenen accés. En lloc de fer-les a la action, es fan en un script post-deploy dins de l'app service d'azure, que s'encarrega de fer les migrations i llançar el servidor.

**Comment by aniolgarcia** [comment]
Tancat per 7d4041295d5dfdc5a3be604ab7cd20840681228a
