### ISSUE TITLE
Crear página con cards

### ISSUE THREAD

**Issue by aliciacarrascoo** [UB-ES-2022-B2/Doogking#9]
Se visualizará el encabezado y el pie de la página.

Aparecerá una lista con las distintas publicaciones tanto en modo Grid como lista. Debe haber un botón que permita cambiar entre los dos layouts.

Debe haber un sistema de paginación de forma que en cada página aparezcan 12 casas y el resto se vayan a las siguientes páginas.

En la parte superior se mostrará una barra de búsqueda para las ciudades, un botón para seleccionar fecha de entrada y salida, otro botón para eliminar filtros y volver a la visualización por defecto y finalmente otro para realizar una búsqueda con estos filtros (implementado en la issue "Añadir botones y campos de fecha check-in check-out y selector ciudad #32")

Para cada publicación se mostrará:
-- Se mostrará una foto
-- La ciudad donde se encuentra la casa
-- La valoración en forma de estrella con un rango del 0 al 5 y un botón con forma de corazón que permita marcar una casa como favorito (solo para usuarios que hayan hecho el login, no funcional).
-- El precio por día de la publicación

Cuando el usuario pase el cursor por encima de la imagen de una casa, se mostrará un botón para accdeder a a esa publicación.

**Comment by PauRodriguezTrens** [comment]
Se visualizará el encabezado y el pie de la página.

Aparecerá una lista con las distintas publicaciones tanto en modo Grid como lista. Debe haber un botón que permita cambiar entre los dos layouts.

Debe haber un sistema de paginación de forma que en cada página aparezcan 12 casas y el resto se vayan a las siguientes páginas.

En la parte superior se mostrará una barra de búsqueda para las ciudades, un botón para seleccionar fecha de entrada y salida, otro botón para eliminar filtros y volver a la visualización por defecto y finalmente otro para realizar una búsqueda con estos filtros (no funcional)

Para cada publicación se mostrará:-- Se mostrará una foto-- La ciudad donde se encuentra la casa-- La valoración en forma de estrella con un rango del 0 al 5 y un botón con forma de corazón que permita marcar una casa como favorito (solo para usuarios que hayan hecho el login, no funcional).-- El precio por día de la publicación

Cuando el usuario pase el cursor por encima de la imagen de una casa, se mostrará un botón para accdeder a a esa publicación.
